CREATE SEQUENCE IF NOT EXISTS USER_ID_SEQ START WITH 100;
CREATE TABLE IF NOT EXISTS USER
(
  ID         INT DEFAULT USER_ID_SEQ.nextval PRIMARY KEY,
  FIRST_NAME VARCHAR(50),
  LAST_NAME  VARCHAR(50),
  USERNAME   VARCHAR(50),
  EMAIL      VARCHAR(50),
  PASSWORD   VARCHAR(300)
);

ALTER TABLE USER
  ADD COLUMN API_KEY VARCHAR(255);

UPDATE USER
SET API_KEY = '1bed9594-c134-4135-9c2a-5794162e0aa9'
WHERE API_KEY IS NULL;

ALTER TABLE USER
  ALTER COLUMN API_KEY VARCHAR(255) NOT NULL;

ALTER TABLE USER
  ALTER COLUMN ID INT DEFAULT USER_ID_SEQ.nextval;

INSERT INTO USER (FIRST_NAME, LAST_NAME, USERNAME, EMAIL, PASSWORD, API_KEY)
VALUES ('Admin', 'Admin', 'administrator', 'no-reply@codete.com',
        '$2a$10$zn4zHom1pGRvsE2PbZtycOieISDR3wmktHahOI5NJyTOOs16IoKrW', '9e1ecdcd-75e7-4a40-9f15-0ec651e813d5');

ALTER TABLE USER_APP
  ADD COLUMN USER NUMBER;

ALTER TABLE USER_APP
  ADD FOREIGN KEY (USER) REFERENCES USER (ID);

UPDATE USER_APP
SET USER = (SELECT ID FROM USER WHERE USERNAME = 'administrator')
WHERE USER IS NULL;

SELECT DISTINCT CONSTRAINT_NAME
FROM INFORMATION_SCHEMA.CONSTRAINTS
WHERE TABLE_NAME = 'USER_APP'
  AND COLUMN_LIST = 'APP_NAME';
ALTER TABLE USER_APP
  DROP CONSTRAINT <NAME_FROM_ABOVE_QUERY>;